# Generated by Django 2.1 on 2018-08-19 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClubToAssociationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField()),
                ('valid_from', models.DateField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_clubtoassociationmemberships', related_query_name='clubtoassociationmembership_approver', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Association')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_clubtoassociationmemberships', related_query_name='clubtoassociationmembership_reporter', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Club')),
            ],
            options={
                'db_table': 'ClubToAssociationMembership',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('founded_on', models.DateField()),
                ('disolved_on', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('zip', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonToAssociationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField()),
                ('valid_from', models.DateField()),
                ('role', models.CharField(choices=[['President', 'President'], ['Vicepresident', 'Vicepresident'], ['Treasurer', 'Treasurer'], ['secretary', 'secretary'], ['Member', 'Member']], max_length=300)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_persontoassociationmemberships', related_query_name='persontoassociationmembership_approver', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Association')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Person')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_persontoassociationmemberships', related_query_name='persontoassociationmembership_reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PersonToAssociationMembership',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerToTeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField()),
                ('valid_from', models.DateField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_playertoteammemberships', related_query_name='playertoteammembership_approver', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Person')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_playertoteammemberships', related_query_name='playertoteammembership_reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PlayerToTeamMembership',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamToClubTeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField()),
                ('valid_from', models.DateField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_teamtoclubteammemberships', related_query_name='teamtoclubteammembership_approver', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Club')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_teamtoclubteammemberships', related_query_name='teamtoclubteammembership_reporter', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Team')),
            ],
            options={
                'db_table': 'TeamToClubTeamMembership',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playertoteammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_management.Team'),
        ),
    ]
