# Generated by Django 2.1.5 on 2019-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='board',
        ),
        migrations.RemoveField(
            model_name='association',
            name='club_members',
        ),
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='association',
            name='board_members',
            field=models.ManyToManyField(through='player_management.PersonToAssociationMembership', to='player_management.Person'),
        ),
        migrations.AddField(
            model_name='association',
            name='member_clubs',
            field=models.ManyToManyField(through='player_management.ClubToAssociationMembership', to='player_management.Club'),
        ),
        migrations.AddField(
            model_name='club',
            name='member_persons',
            field=models.ManyToManyField(through='player_management.PersonToClubMembership', to='player_management.Person'),
        ),
        migrations.AddField(
            model_name='team',
            name='member_persons',
            field=models.ManyToManyField(through='player_management.PersonToTeamMembership', to='player_management.Person'),
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='dissolved_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='dissolved_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[['m', 'm'], ['f', 'f']], max_length=1),
        ),
        migrations.AlterField(
            model_name='persontoassociationmembership',
            name='role',
            field=models.CharField(choices=[['President', 'President'], ['Vicepresident', 'Vicepresident'], ['Treasurer', 'Treasurer'], ['secretary', 'secretary']], max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='dissolved_on',
            field=models.DateField(null=True),
        ),
    ]
