language: node_js
node_js:
  - "11"

cache: npm

script: cd frontend && npm install && npm run build:prod && cd ..

before_deploy:
- cd frontend/dist/apps/frisbeedb
- tar -cvf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar *

deploy:
  provider: releases
  api_key:
    secure: $deploy_key
  file:
    - ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar
  skip_cleanup: true
  on:
    tags: true
