version: "3.6"

services:
  db:
    build: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: backend
    restart: always
    ports:
      - "8000:8080" # map gunicorn to port 8000
    depends_on:
      - db
    volumes:
      - static_data:/static_data
      - ./backend:/workspace
      - ./backend/credentials:/etc/credentials
  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - static_data:/www/data/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # angular:
  #   build: frontend
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - django

volumes:
  postgres_data:
  static_data:
