version: "3.6"

services:
  db:
    build: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  django:
    build: backend
    restart: always
    depends_on:
      - db
    volumes:
      - static_data:/static_data
      - media_data:/media
      - ./backend:/workspace
      - ./backend/credentials:/etc/credentials
    environment:
      - ENVIRONMENT=production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/www/data/static
      - media_data:/www/data/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/data/conf:/etc/letsencrypt
      - ./certbot/data/www:/var/www/certbot
    # reload config every 6h
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    restart: always
    depends_on:
      - django
      - certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/data/conf:/etc/letsencrypt
      - ./certbot/data/www:/var/www/certbot
    #renew certs every 12h
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  postgres_data:
  static_data:
  media_data:
