version: "3.6"

services: 
  db:
    build: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - '5432:5432'

  django:
    build: backend
    ports:
      - '8000:8000'
      - '3500:3500'
    depends_on: 
      - db
    entrypoint: ["/bin/bash","-c","cd backend && python manage.py makemigrations --no-input && python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"]

  # angular:
  #   build: frontend
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - django


volumes:
  postgres_data:
