version: "3.7"

services: 
  db:
    #container_name: frisbee-postgres-db
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - '5432:5432'

  django-apache2:
    build: .
    container_name: frisbee-django-apache2
    ports:
      - '8005:80'
      - '3500:3500'
      - '8006:81'
    volumes: 
      - $PWD/../backend:/var/www/html/backend
    depends_on: 
      - db

volumes:
  postgres_data:
