--- #-------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
version: "3.6"
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file

  devcontainer:
    build: backend
    ports:
      - "8081:8000" # dev server
    depends_on:
      - db
    volumes:
      - .:/workspace
    entrypoint: ["bash", "-c", "sleep infinity"]
  django:
    ports:
      - 8082:8080 #gunicorn server
  nginx:
    build: nginx
    ports:
      - 8083:80 #nginx frontend
