--- #-------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
version: "3.6"
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file

  devcontainer:
    image: ulti-players_django:latest
    ports:
      - "8081:8000" # expose django dev server
    depends_on:
      - db
    volumes:
      - .:/workspace
      - static_data:/static_data
      - media_data:/media
      - ./backend/credentials:/etc/credentials
      - test-results:/test-results
    entrypoint: ["bash", "-c", "sleep infinity"]
    environment:
      - ENVIRONMENT=development
  django:
    ports:
      - 8082:8080 # expose gunicorn server
  nginx:
    ports:
      - "8083:80" # expose nginx webserver under nonstandard port
      - "8443:443"
    volumes:
      - test-results:/www/data/tests # mount test results html
  db:
    ports:
      - "5432:5432" #expose database port for development
volumes:
  test-results:
