"""
Django settings for ultimate_frisbee_management project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db', # set in docker-compose.yml
        'PORT': 5432 # default postgres port
    }
}

#SILKY_PYTHON_PROFILER = True
#SILKY_PYTHON_PROFILER_BINARY = True

#for debug toolbar
INTERNAL_IPS = (
    '127.0.0.1',
    'localhost',
    '0.0.0.0',
    '172.18.0.1',
    '62.178.108.138'
)